unitedstates/inspectors-general

- inspectors/va.py
Use `Department of Veterans Affairs`.
Done after seeing "Office of Information and Technology (OIT)" listed as the agency name [on a report](https://scout.sunlightfoundation.com/item/document/ig_report-va-2015-13-03324-85/inspector-general-report-follow-up-audit-of-the-information-technology-project-management-accountability-system).
> Don't use VA office names for agency name

- inspectors/archives.py
- inspectors/energy.py
- inspectors/gpo.py
- inspectors/hhs.py
- inspectors/ncua.py
- inspectors/nsf.py
- inspectors/pbgc.py
- inspectors/treasury.py
- inspectors/usps.py
- inspectors/utils/inspector.py
- inspectors/utils/utils.py
- safe.yml
This catches up on a couple months of scrapers going to seed. Most of the fixes are small and scraper-specific, and I suggest just looking at the commits. 
But a few notes:
* All important report strings (e.g. `summary`, `title`) get unicode spaces replaced with normal spaces now.
* `www.ignet.gov` has misconfigured HTTPS, and so I've whitelisted it and provided a way to disable verification only to whitelisted domains.
* When doing the verification whitelist, I found a bug in scrapelib, [filed here](https://github.com/sunlightlabs/scrapelib/issues/31). When it's fixed, we can remove the direct `requests.get` call for non-binary downloads. I left the `scraperlib.urlretrieve` call in for binary downloads, rather than re-implement scrapelib's urlretrieve method, so we are currently …
> Big batch of scraper fixes

- inspectors/itc.py
The `itc` scraper had stopped getting anything at all, without any warnings or errors. I noticed this because the `itc` directory wasn't there at all in the new archive I made in November, so the scraper had already broken by then without warning.
This rewrites the scraper to handle Audit reports, but not for [Semiannual](http://usitc.gov/oig/semiannual_reports.htm) or [Peer Reviews](http://usitc.gov/oig/peer_reviews.htm). They shouldn't be hard to do. If anyone wants to hop in on this branch and finish the job, I'd much appreciate it.
I've also added a check at the top of the scraper that throws an exception if it finds 0 reports on the audits page. The scrapers should make a point to choke if unexpected behavior happens that suggests a too-graceful handling of changed markup.
> Partially resuscitate ITC OIG scraper

- inspectors/prc.py
I believe this should keep report_ids stable, since they're based on report filenames.
> New PRC scraper, ref gh-202

- inspectors/nrc.py
References #200. NRC semiannual reports _are_ still in a table, but that table is now in a [different place](http://www.nrc.gov/reading-rm/doc-collections/nuregs/staff/sr1415/index.html).
> new url for NRC semiannual reports

- requirements.txt
This should also address some recurring `sba` failures.
> Lock the version of requests explicitly

- inspectors/utils/utils.py
Good news: The FCA website now has a SHA-2 certificate
Bad news: The certificate chain provided by the server only goes back to the new Entrust SHA-2 root CA, and does not include the cross-signed certificate from the old SHA-1 root CA
>  [fca] Skip certificate validation

- inspectors/sba.py
- inspectors/usps.py
These changes will retry individual pages of the search results to get missing reports. This fixes the second half of #214.
> USPS pagination fixes

- inspectors/state.py
Good for them!
```
$ curl --head http://oig.state.gov
HTTP/1.1 301 Moved Permanently
Server: AkamaiGHost
Content-Length: 0
Location: https://oig.state.gov/
Date: Tue, 07 Apr 2015 02:43:08 GMT
Connection: keep-alive
access-control-allow-origin: http://search.state.gov
```
> State OIG moved to HTTPS

- inspectors/cncs.py
- inspectors/cpsc.py
- inspectors/education.py
- inspectors/flra.py
- inspectors/labor.py
- inspectors/nrc.py
- inspectors/treasury.py
- inspectors/utils/inspector.py
- inspectors/utils/utils.py
- inspectors/va.py
This branch takes care of a batch of easy scraper issues. One thing I'd like to draw your attention to is c1d0a01. The NRC website no longer includes brochures from the OIG with the rest of their brochures. We were previously collecting these as "other" reports.
> Misc fixes

- inspectors/doj.py
- inspectors/utils/utils.py
The OIG's website has moved from http://www.justice.gov/oig/ to
https://oig.justice.gov/
> [doj] Fix URLs for new subdomain, misc. cleanup

- inspectors/loc.py
Here's what I have so far for #230. I've started getting 503 errors for PDFs, both over http and https, which is hampering testing.
I had to make another change to the code, in the semiannual reports section. The selector code there was tripping up on an analytics <script> tag, and I was getting a `NoReportsFoundError` from it. This wasn't showing up in the #errors channel, which seems suspicious.
> [WIP] [loc] HTTPS URLs and other cleanup

- inspectors/lsc.py
Fixes #233. Some older reports, especially those related to the "mapping project," have broken links. I plan on dealing with those as part of #204, by extracting the relevant files from https://www.oig.lsc.gov/images/mapping/mapping.zip.
> [lsc] Rewrite scraper for new website

- inspectors/dod.py
- inspectors/gsa.py
- inspectors/smithsonian.py
- inspectors/utils/utils.py
- scripts/soft_404.py
Some servers do not properly return an error status code when they can't find the page for a URL. This pull request will register a requests TransportAdapter for these servers to detect such cases and throw an exception.
In most cases, the server first gives a redirect to a "page not found" page, which is in turn served with a 200 status code. In those cases, the TransportAdapter checks the redirect URL against a blacklist, and raises an exception based on that. For other sites where no redirect is involved, and the server always responds with a status code of 200, the TransportAdapter will check a telltale header, read the data, and check it for specific strings. If the TransportAdapter had to read the body of a response, it will mock up a new response to pass along the data.
So far, I …
> Detect "Soft 404s"

- inspectors/gpo.py
The GPO OIG just added several unpublished reports that all started with `Information Security: Penetration Testing of GPO's`, so the report IDs all ended up being the same. Doubling the allowed length will fix the issue.
> [gpo] Allow longer report IDs

- inspectors/va.py
Ran across this while looking at mapping properties, this will properly insert whitespace between cities in the "location" field.
> [va] Handle <br> in location (and other metadata)

- requirements.txt
DOT's certificate chains up to the newer Entrust G2 CA, which is not in
requests. If certifi is installed, requests will use that bundle, which
includes the new root.
> [dot] Add certifi to requirements.txt for Entrust

- inspectors/utils/utils.py
This is a followup from #245, see [this comment](https://github.com/unitedstates/inspectors-general/pull/245#issuecomment-142768185).
Older versions of OpenSSL have issues building the correct certificate chain in the presence of cross-signed CAs. When communicating with servers that trigger this problem, (i.e. SBA and SIGAR) we should instead use certifi's legacy bundle, which includes roots that issued SHA-1 certificates.
Newer versions of OpenSSL have features and options to improve the situation, such as X509_V_FLAG_TRUSTED_FIRST and a new "alternate chains" algorithm. However, X509_V_FLAG_TRUSTED_FIRST is not yet exposed to Python; `ssl.VERIFY_X509_TRUSTED_FIRST` will first be released in the forthcoming Python 3.4.4, where it will be set by default. The alternate chains algorithm …
> SHA-1 CA bundle

- inspectors/amtrak.py
The Amtrak website was redesigned recently, this takes care of the changes. (Yay, no tables!) I spot-checked the contents, and it looks like all the reports are still there, just organized and presented differently.
Much like with the USPS site, pagination of reports is not stable. If multiple reports with the same published date span two pages of search results, then those reports will show up in different orders from page load to page load. Thus, fetching each page once may miss some reports. For this scraper, I solved the issue by getting all of the results for each query on one page.
> Revise Amtrak scraper

- inspectors/utils/utils.py
`pdftotext` inserts a form feed character by default at each page break. This adds a command line switch to disable that behavior, since we don't use it, and it causes problems further down the toolchain.
> Don't use form feed char in PDF text extraction

- inspectors/cpsc.py
- inspectors/denali.py
- inspectors/dod.py
- inspectors/epa.py
- inspectors/fmc.py
- inspectors/lsc.py
This fixes six different scrapers that have been showing up in [#errors](https://oversight.slack.com/messages/errors) lately. Mostly dates, bookkeeping, and heuristic fixes.
> More fixes

- inspectors/ncua.py
- inspectors/utils/utils.py
NCUA is now all-HTTPS, though the chain is incomplete. (I emailed the webmaster about that) FHFA works now, and can be taken off the whitelist. CIGIE is still serving an incomplete chain.
> TLS changes

- inspectors/utils/utils.py
This cuts the number of processes spawned in half by memoizing whether each conversion tool is present. In unscientific testing with one scraper, this cut a five to seven second runtime down to four seconds.
> Cache tool presence

- inspectors/archives.py
- inspectors/cpb.py
- inspectors/epa.py
- inspectors/gsa.py
- inspectors/itc.py
- inspectors/labor.py
- inspectors/lsc.py
- inspectors/ncua.py
- inspectors/peacecorps.py
- inspectors/ssa.py
- inspectors/tigta.py
- inspectors/treasury.py
- inspectors/utils/inspector.py
- inspectors/utils/utils.py
Here are more scraper fixes. The first half are general upkeep, and the second half are for handling errors that arise from the fact that it's 2016 and there aren't any 2016-dated reports.
> Scraper fixes

- .travis.yml
- inspectors/doj.py
- inspectors/eac.py
- inspectors/education.py
- inspectors/flra.py
- inspectors/sigar.py
- inspectors/sigtarp.py
Pyflakes wss not warning on duplicate keys in dictionary literals. In
each case, only the last value will remain in the dictionary. As a
result, some pages were not being crawled. This fixes the six scrapers
with the issue and adds pylint to the CI script to prevent regressions.
> Fix dictionaries with duplicate keys

- inspectors/osc.py
I have created a scraper for Office of Special Counsel, an important entity that investigates whistleblower retaliation and other prohibited practices across all federal agencies. The scraper parses 1,137 reports going back to 2009.
Next, if you want it, I plan to contribute a module that will be the most effective way of solving your "incorporating manually FOIA'd reports" problem. It will be a scraper for GovernmentAttic.org, which has over 2,000 FOIA'd reports, mostly IG reports, and is regularly updated with new ones.
> Added osc.py, Office of Special Counsel. 1,137 reports since 2009

- inspectors/nrc.py
The audit report pages for 1995-2004 have been taken off the website, and in their place there are now two new pages that list selected reports from that time period. One lists those "that resulted in
substantive changes in agency policy and procedures," and one lists those with recommendations that have not yet been closed out.
> [nrc] Handle new site layout (old reports removed)

- inspectors/ssa.py
This addresses part of konklone/oversight.garden#73. For any investigation without a PDF link, the announcement page is downloaded as the report itself. This removes the bulk of false positives, while leaving all the "Limited Distribution" audit reports.
> [ssa] Improve unreleased report heuristic

- inspectors/doj.py
- inspectors/utils/utils.py
This patches up the DOJ scraper to pick up some pages and links that weren't being parsed properly, and adds additional "no reports found" checks.
> [doj] Missing reports

- inspectors/gaoreports.py
Much belatedly, here is a scraper for GAO reports and restricted reports per #269. It gathers 52,000 reports--90GB--dating back to 1940, though the default year for archiving is set to 1970 here.
> Adding GAO reports (not GAO IG)
